vscode:
    extensions:
      - connorshea.vscode-ruby-test-adapter@0.6.1:HO9rpcRv7bmRIuo7Mty/zg==
      - hbenl.vscode-test-explorer@2.15.0:koqDUMWDPJzELp/hdS/lWw==
      - rebornix.ruby@0.26.0:RN+gv0dPjYfMqlcEEralhg==
      - wingrunr21.vscode-ruby@0.26.0:VakXVw0C77hAQ3U3AZTn1Q==
      - kaiwood.endwise@1.4.2:b9UKVcoO63LrGqSpDkA2mg==
